<a href="https://colab.research.google.com/github/SarahSouzaPontes/analise_dados_dengue/blob/main/Qualidade_dos_Dados_pynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
import pandas as pd
import matplotlib.pyplot as plt

# Carregue o arquivo CSV em um DataFrame, especificando o separador como ';'
df = pd.read_csv('/content/sample_data/dengue.csv', sep=';')
df

<ipython-input-38-f0891ec1ecca>:5: DtypeWarning: Columns (27,49,51,88,104) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/sample_data/dengue.csv', sep=';')


NU_NOTIFIC                       ID_PESSOA  \
0           10110  291800-291800-1982-06-23-M-4.0   
1            1994  291800-291800-1984-07-26-M-4.0   
2            5321  291890-291890-1988-06-22-F-2.0   
3           15811  293105-293105-2004-12-29-F-2.0   
4           23461  293105-293105-1961-01-25-M-2.0   
...           ...                             ...   
38564       19618  291080-291080-1985-10-04-F-9.0   
38565        6805  292740-292740-1981-05-01-M-4.0   
38566       16531  292740-292740-1996-10-04-M-9.0   
38567       31594  292740-292740-1991-07-05-F-9.0   
38568        1174  292740-292740-1957-10-01-F-4.0   

                                           NOME  COMUNINF  ID_MN_RESI  \
0            ALBERTO GARCIA MACIEL FILHO AGUIAR  290060.0      291800   
1                        MARCIO RIBEIRO FONSECA       NaN      291800   
2          SOLANGE MOREIRA SANTOS CARDOSO ASSIS  291890.0      291890   
3                         PATRICIA BORGES ROCHA  293105.0      293105   
4      WALTER AMARAL RIBEIRO RODRIGUES PINHEIRO  293105.0      293105   
...                                         ...       ...         ...   
38564              NEUZA SOUSA FERNANDES AGUIAR       NaN      291080   
38565       MARCELO MORAES MIRANDA NUNES COELHO       NaN      292740   
38566               JOAQUIM MACEDO CORREIA MELO       NaN      292740   
38567                     LIDIA TAVARES CORREIA       NaN      292740   
38568                         OLGA PINTO FARIAS       NaN      292740   

       ID_MUNICIP  MUNICIPIO  TP_NOT ID_AGRAVO  DT_NOTIFIC  ...  MUN_HOSP  \
0          291800        NaN       2       A90  2012-12-31  ...       NaN   
1          291800        NaN       2       A90  2013-01-01  ...       NaN   
2          291890        NaN       2       A90  2013-01-01  ...       NaN   
3          293105        NaN       2       A90  2013-01-01  ...       NaN   
4          293105        NaN       2       A90  2013-01-01  ...       NaN   
...           ...        ...     ...       ...         ...  ...       ...   
38564      291080        NaN       2       A90  2019-12-28  ...       NaN   
38565      292740        NaN       2       A90  2019-12-28  ...       NaN   
38566      292740        NaN       2       A90  2019-12-28  ...       NaN   
38567      292740        NaN       2       A90  2019-12-28  ...       NaN   
38568      292740        NaN       2       A90  2019-12-28  ...       NaN   

       UF_HOSP      MUN_SAUDENOT  UF_SAUDENOT         MUNI_RESI UF_RESI  \
0          NaN            JEQUIE           29            JEQUIE      29   
1          NaN            JEQUIE           29            JEQUIE      29   
2          NaN           LAJEDAO           29           LAJEDAO      29   
3          NaN       TANQUE NOVO           29       TANQUE NOVO      29   
4          NaN       TANQUE NOVO           29       TANQUE NOVO      29   
...        ...               ...          ...               ...     ...   
38564      NaN  FEIRA DE SANTANA           29  FEIRA DE SANTANA      29   
38565      NaN          SALVADOR           29          SALVADOR      29   
38566      NaN          SALVADOR           29          SALVADOR      29   
38567      NaN          SALVADOR           29          SALVADOR      29   
38568      NaN          SALVADOR           29          SALVADOR      29   

         MUN_INFEC UF_INFEC  IDADE SEM_PRI_V  
0          AIQUARA     29.0   30.0       1.0  
1              NaN      NaN   28.0       1.0  
2          LAJEDAO     29.0   24.0       1.0  
3      TANQUE NOVO     29.0    8.0       1.0  
4      TANQUE NOVO     29.0   51.0       1.0  
...            ...      ...    ...       ...  
38564          NaN      NaN   34.0      52.0  
38565          NaN      NaN   38.0      52.0  
38566          NaN      NaN   23.0      52.0  
38567          NaN      NaN   28.0      52.0  
38568          NaN      NaN   62.0      52.0  

[38569 rows x 143 columns]

In [48]:
# Exibir todas as colunas do DataFrame
print("Todas as colunas do DataFrame:")
for coluna in df.columns:
    print(coluna)


Todas as colunas do DataFrame:
NU_NOTIFIC
ID_PESSOA
NOME
COMUNINF
ID_MN_RESI
ID_MUNICIP
MUNICIPIO
TP_NOT
ID_AGRAVO
DT_NOTIFIC
SEM_NOT
NU_ANO
SG_UF_NOT
ID_REGIONA
ID_UNIDADE
DT_SIN_PRI
SEM_PRI
DT_NASC
NU_IDADE_N
CS_SEXO
CS_GESTANT
CS_RACA
CS_ESCOL_N
SG_UF
ID_RG_RESI
ID_PAIS
DT_INVEST
ID_OCUPA_N
FEBRE
MIALGIA
CEFALEIA
EXANTEMA
VOMITO
NAUSEA
DOR_COSTAS
CONJUNTVIT
ARTRITE
ARTRALGIA
PETEQUIA_N
LEUCOPENIA
LACO
DOR_RETRO
DIABETES
HEMATOLOG
HEPATOPAT
RENAL
HIPERTENSA
ACIDO_PEPT
AUTO_IMUNE
DT_CHIK_S1
DT_CHIK_S2
DT_PRNT
RES_CHIKS1
RES_CHIKS2
RESUL_PRNT
DT_SORO
RESUL_SORO
DT_NS1
RESUL_NS1
DT_VIRAL
RESUL_VI_N
DT_PCR
RESUL_PCR_
SOROTIPO
HISTOPA_N
IMUNOH_N
HOSPITALIZ
DT_INTERNA
UF
TPAUTOCTO
COUFINF
COPAISINF
CLASSI_FIN
CRITERIO
DOENCA_TRA
CLINC_CHIK
EVOLUCAO
DT_OBITO
DT_ENCERRA
ALRM_HIPOT
ALRM_PLAQ
ALRM_VOM
ALRM_SANG
ALRM_HEMAT
ALRM_ABDOM
ALRM_LETAR
ALRM_HEPAT
ALRM_LIQ
DT_ALRM
GRAV_PULSO
GRAV_CONV
GRAV_ENCH
GRAV_INSUF
GRAV_TAQUI
GRAV_EXTRE
GRAV_HIPOT
GRAV_HEMAT
GRAV_MELEN
GRAV_METRO
GRAV_SANG
GRAV_A

In [92]:
# Suponha que df seja o seu DataFrame

# Visualizar os valores únicos da coluna 'CS_ESCOL_N'
valores_unicos_cs_escol_n = df['CS_ESCOL_N'].unique()

# Exibir os valores únicos da coluna 'CS_ESCOL_N'
print("Valores únicos da coluna 'CS_ESCOL_N':")
print(valores_unicos_cs_escol_n)


Valores únicos da coluna 'CS_ESCOL_N':
[ 6. nan  9.  7.  3.  8. 10.  5.  4.  2.  1.  0.]


In [91]:
# Suponha que df seja o seu DataFrame

# Visualizar os valores únicos da coluna 'ID_OCUPA_N'
valores_unicos_id_ocupa_n = df['ID_OCUPA_N'].unique()

# Exibir os valores únicos da coluna 'ID_OCUPA_N'
print("Valores únicos da coluna 'ID_OCUPA_N':")
print(valores_unicos_id_ocupa_n)


Valores únicos da coluna 'ID_OCUPA_N':
[342305.0 nan 998999.0 951105.0 999991.0 231205.0 422215.0 999992.0
 763210.0 261140.0 715505.0 331110.0 999994.0 521135.0 142320.0 513315.0
 715210.0 621005.0 999993.0 516205.0 254310.0 331205.0 782305.0 514215.0
 512105.0 524305.0 782405.0 142530.0 111120.0 782510.0 141410.0 223605.0
 333115.0 724110.0 331105.0 622020.0 516105.0 763320.0 613405.0 261415.0
 352210.0 515105.0 521105.0 764305.0 351505.0 412110.0 223505.0 223620.0
 521110.0 411005.0 421125.0 252210.0 715615.0 322230.0 784105.0 613005.0
 512110.0 322205.0 992225.0 631010.0 524205.0 212315.0 422105.0 354705.0
 723310.0 517330.0 632520.0 782505.0 514210.0 782315.0 516110.0 324115.0
 631020.0 612005.0 514115.0 111220.0 422205.0 517420.0 141405.0 239425.0
 252305.0 782410.0 321105.0 231320.0 241005.0 521130.0 910105.0 512120.0
 716610.0 411010.0 763010.0 414210.0 848305.0 232115.0 761820.0 862305.0
 725010.0 231210.0 252105.0 239405.0 848510.0 841408.0 131110.0 764005.0
 516210.0 515215.

In [90]:
# Suponha que df seja o seu DataFrame

# Visualizar os valores únicos da coluna 'SEM_NOT'
valores_unicos_sem_not = df['SEM_NOT'].unique()

# Exibir os valores únicos da coluna 'SEM_NOT'
print("Valores únicos da coluna 'SEM_NOT':")
print(valores_unicos_sem_not)


Valores únicos da coluna 'SEM_NOT':
[201301 201302 201303 201304 201305 201306 201307 201308 201309 201310
 201311 201312 201313 201314 201315 201316 201317 201318 201319 201320
 201321 201322 201323 201324 201325 201326 201327 201328 201329 201330
 201331 201332 201333 201334 201335 201336 201337 201338 201339 201340
 201341 201342 201343 201344 201345 201346 201347 201348 201349 201350
 201351 201352 201401 201402 201403 201404 201405 201406 201407 201408
 201409 201410 201411 201412 201413 201414 201415 201416 201417 201418
 201419 201420 201421 201422 201423 201424 201425 201426 201427 201428
 201429 201430 201431 201432 201433 201434 201435 201436 201437 201438
 201439 201440 201441 201442 201443 201444 201445 201446 201447 201448
 201449 201450 201451 201452 201453 201501 201502 201503 201504 201505
 201506 201507 201508 201509 201510 201511 201512 201513 201514 201515
 201516 201517 201518 201519 201520 201521 201522 201523 201524 201525
 201526 201527 201528 201529 201530 20153

In [72]:
# Lista das colunas a serem verificadas
colunas_distinct = ['MUN_HOSP', 'UF_HOSP', 'MUN_SAUDENOT', 'UF_SAUDENOT',
                    'MUNI_RESI', 'UF_RESI', 'MUN_INFEC', 'UF_INFEC',
                    'IDADE', 'SEM_PRI_V']

# Exibir os valores únicos de cada coluna
for coluna in colunas_distinct:
    valores_unicos = df[coluna].unique()
    print(f"Valores únicos da coluna '{coluna}':")
    print(valores_unicos)
    print()


Valores únicos da coluna 'MUN_HOSP':
[nan 'VALENTE' 'BOTUPORA' 'GUANAMBI' 'MEDEIROS NETO' 'SERRA DOURADA'
 'BRUMADO' 'ALCOBACA' 'ITAMARAJU' 'JEQUIE' 'MUCURI' 'IBIRATAIA'
 'CICERO DANTAS' 'IUIU' 'UNA' 'EUNAPOLIS' 'PORTO SEGURO' 'UAUA' 'IBICUI'
 'TANQUE NOVO' 'SENTO SE' 'SENHOR DO BONFIM' 'SALVADOR' 'PARAMIRIM'
 'SEABRA' 'ITAGIBA' 'IBIPITANGA' 'SATIRO DIAS' 'LAJEDO DO TABOCAL'
 'BARREIRAS' 'WAGNER' 'RIACHAO DAS NEVES' 'ENCRUZILHADA' 'ESPLANADA'
 'CACULE' 'IRECE' 'CACHOEIRA' 'CAFARNAUM' 'IBITITA' 'CATURAMA' 'IPIAU'
 'BRASILIA' 'MORRO DO CHAPEU' 'FEIRA DE SANTANA' 'MARACAS' 'JUAZEIRO'
 'AMERICA DOURADA' 'POCOES' 'AIQUARA' 'IRAMAIA' 'ILHEUS' 'JAGUAQUARA'
 'VARZEA DO POCO' 'RIO DE CONTAS' 'ITABELA' 'PLANALTINO' 'CARAVELAS'
 'CASTRO ALVES' 'ITAJU DO COLONIA' 'CRAVOLANDIA' 'MACARANI' 'JACOBINA'
 'JUCURUCU' 'BAIXA GRANDE' 'SANTO ANTONIO DE JESUS' 'ITIRUCU' 'IPIRA'
 'CONDEUBA' 'CAEM' 'UIBAI' 'GANDU' 'ITACARE' 'CAATIBA' 'ITAPEBI'
 'ANDORINHA' 'ITABUNA' 'UBATA' 'SAPEACU' 'IBITIARA' 'CANDIDO SALES'

In [79]:
# Filtrar o DataFrame para as linhas onde a idade é menor que 18
idade_menor_que_18 = df[df['IDADE'] < 18]

# Retornar as colunas "Dt_Nasc" e "IDADE" para essas linhas
dt_nasc_idade_abaixo_de_18 = idade_menor_que_18[['DT_NASC', 'IDADE', 'DT_NOTIFIC']]

# Exibir as datas de nascimento e as idades onde a idade é menor que 18
print("Datas de nascimento e idades onde a idade é abaixo de 18:")
print(dt_nasc_idade_abaixo_de_18)


Datas de nascimento e idades onde a idade é abaixo de 18:
          DT_NASC  IDADE  DT_NOTIFIC
3      2004-12-29    8.0  2013-01-01
7      2000-09-05   12.0  2013-01-02
14     1995-01-20   17.0  2013-01-03
21     2007-12-24    5.0  2013-01-04
22     2000-10-28   12.0  2013-01-04
...           ...    ...         ...
38547  2012-01-03    7.0  2019-12-27
38552  2002-02-09   17.0  2019-12-27
38553  2017-02-20    2.0  2019-12-27
38554  2018-06-12    1.0  2019-12-27
38561  2017-06-20    2.0  2019-12-28

[10068 rows x 3 columns]


In [88]:
import pandas as pd

# Suponha que df seja o DataFrame

# Convertendo as colunas de datas para o tipo datetime
df[['DT_NOTIFIC', 'DT_NASC']] = df[['DT_NOTIFIC', 'DT_NASC']].apply(pd.to_datetime)

# Calcular a diferença em dias entre DT_NOTIFIC e DT_NASC e depois em anos
df['DIFERENCA_ANOS'] = abs((df['DT_NOTIFIC'] - df['DT_NASC']).dt.days) // 365

# Exibir as colunas de idade e diferença em anos lado a lado
print(df[['IDADE', 'DIFERENCA_ANOS']])



       IDADE  DIFERENCA_ANOS
0       30.0              30
1       28.0              28
2       24.0              24
3        8.0               8
4       51.0              51
...      ...             ...
38564   34.0              34
38565   38.0              38
38566   23.0              23
38567   28.0              28
38568   62.0              62

[38569 rows x 2 columns]


In [89]:
import pandas as pd

# Suponha que df seja o DataFrame

# Convertendo as colunas de datas para o tipo datetime
df[['DT_NOTIFIC', 'DT_NASC']] = df[['DT_NOTIFIC', 'DT_NASC']].apply(pd.to_datetime)

# Calcular a diferença em dias entre DT_NOTIFIC e DT_NASC e depois em anos
df['DIFERENCA_ANOS'] = abs((df['DT_NOTIFIC'] - df['DT_NASC']).dt.days) // 365

# Comparar apenas os dois primeiros dígitos da idade e da diferença em anos
df['IDADE_PRIMEIROS_DIGITOS'] = df['IDADE'].astype(str).str[:2]
df['DIFERENCA_ANOS_PRIMEIROS_DIGITOS'] = df['DIFERENCA_ANOS'].astype(str).str[:2]

# Exibir as condições na tela
print("Comparando os dois primeiros dígitos da idade e da diferença em anos:")
print(df[['IDADE_PRIMEIROS_DIGITOS', 'DIFERENCA_ANOS_PRIMEIROS_DIGITOS']])


Comparando os dois primeiros dígitos da idade e da diferença em anos:
      IDADE_PRIMEIROS_DIGITOS DIFERENCA_ANOS_PRIMEIROS_DIGITOS
0                          30                               30
1                          28                               28
2                          24                               24
3                          8.                                8
4                          51                               51
...                       ...                              ...
38564                      34                               34
38565                      38                               38
38566                      23                               23
38567                      28                               28
38568                      62                               62

[38569 rows x 2 columns]


In [63]:
# Verificar duplicatas com base em ID_PESSOA, NU_NOTIFIC e NOME
duplicatas = df[df.duplicated(subset=['ID_PESSOA', 'NU_NOTIFIC', 'NOME'], keep=False)]

# Exibir os casos duplicados com base nessas colunas
if not duplicatas.empty:
    print("Casos duplicados encontrados:")
    print(duplicatas)
else:
    print("Não há casos duplicados.")


Não há casos duplicados.


In [67]:
# Verificar duplicatas na coluna ID_PESSOA
duplicatas_NOME = df[df.duplicated(subset=['NOME'], keep=False)]

# Exibir os números repetidos na coluna ID_PESSOA
if not duplicatas_NOME.empty:
    print("Números repetidos na coluna NOME:")
    print(duplicatas_NOME['NOME'].unique())
else:
    print("Não há números repetidos na coluna NOME.")


Números repetidos na coluna NOME:
['IRACI ABREU AGUIAR' 'SERGIO MARTINS LIMA RAMOS'
 'MARIANA FERREIRA CARVALHO CAMPOS ALVES'
 'RONALDO OLIVEIRA SOARES OLIVEIRA' 'IRENE FERREIRA VIEIRA AGUIAR BO'
 'HILDA LAUDO SOUZA' 'CECILIA MATOS CARDOSO CARDOSO VIANA'
 'TANIA MATOS JUNIOR SANTANA SOUZA' 'IZABEL SOARES GUIMARAES ROSA'
 'MANOEL CORREIA GARCIA' 'MARLI MIRANDA REIS CARNEIRO'
 'RITA BARROS MENEZES AMORIM RIBEIRO' 'SEVERINA MENDES AMORIM FREITAS'
 'TERESINHA MELO SILVA' 'LEONARDO SANTOS LEITE'
 'ANGELINA SILVA ROCHA ABREU FREITAS'
 'FRANCISCA DUARTE FARIAS LEITE SOARES' 'IRACEMA GARCIA CORREIA'
 'VALDEMAR MONTEIRO NETO' 'NATIMORTO CARVALHO ABREU RODRIGUES TAVARES'
 'MARILENE FERNANDES CARDOSO' 'MARILENE CAMPOS AZEVEDO'
 'FRANCISCO MENDES GARCIA MOTA' 'GUILHERME ANDRADE ASSIS ABREU MELO'
 'BEATRIZ ROBERTO PEREIRA FONSECA' 'JOAQUIM CESAR ANDRADE SOUZA'
 'BRUNO CARDOSO MOURA' 'BEATRIZ CAMPOS SILVA MORAIS TEIXEIRA'
 'OLIVIA ABREU OLIVEIRA CAVALCANTE GUIMARAES'
 'ROSALINA MONTEIRO ASSIS SOUZA'

In [70]:
# Verificar duplicatas na coluna NU_NOTIFIC
duplicatas_NU_NOTIFIC = df[df.duplicated(subset=['NU_NOTIFIC'], keep=False)]

# Exibir os números repetidos na coluna NU_NOTIFIC
if not duplicatas_NU_NOTIFIC.empty:
    print("Números repetidos na coluna NU_NOTIFIC:")
    print(duplicatas_NU_NOTIFIC[['NU_NOTIFIC']].drop_duplicates())
else:
    print("Não há números repetidos na coluna NU_NOTIFIC.")


Não há números repetidos na coluna NU_NOTIFIC.


In [69]:
# Verificar duplicatas na coluna ID_PESSOA
duplicatas_ID_PESSOA = df[df.duplicated(subset=['ID_PESSOA'], keep=False)]

# Exibir os nomes repetidos associados aos IDs duplicados
if not duplicatas_ID_PESSOA.empty:
    print("Nomes associados aos IDs PESSOA duplicados:")
    print(duplicatas_ID_PESSOA[['ID_PESSOA', 'NOME']].drop_duplicates())
else:
    print("Não há IDs PESSOA duplicados.")


Nomes associados aos IDs PESSOA duplicados:
                            ID_PESSOA                                    NOME
25     290320-290320-2006-09-04-F-4.0                      IRACI ABREU AGUIAR
84     292870-292870-1999-11-27-M-9.0               SERGIO MARTINS LIMA RAMOS
93     293135-293135-1982-08-18-F-4.0  MARIANA FERREIRA CARVALHO CAMPOS ALVES
115    292740-292740-1983-06-14-M-9.0        RONALDO OLIVEIRA SOARES OLIVEIRA
148    293135-293135-1970-03-13-F-4.0         IRENE FERREIRA VIEIRA AGUIAR BO
...                               ...                                     ...
37074  292740-292740-1969-04-08-F-9.0                   ELVIRA RIBEIRO MACIEL
37193  290980-290980-1990-10-19-F-2.0          IRACEMA SILVEIRA FRANCA BORGES
37924  292740-292740-1997-01-12-F-2.0         ISABEL CESAR MONTEIRO RODRIGUES
38382  292740-292740-1977-07-29-F-9.0                  LUCIA FREITAS PINHEIRO
38548  291080-291080-1979-06-03-F-9.0   CELINA MACEDO SIQUEIRA MIRANDA AMORIM

[351 rows x 2 colum

In [71]:
# Verificar duplicatas na coluna ID_PESSOA
duplicatas_ID_PESSOA = df[df.duplicated(subset=['ID_PESSOA'], keep=False)]

# Exibir as linhas completas dos registros duplicados na coluna ID_PESSOA
if not duplicatas_ID_PESSOA.empty:
    print("Registros duplicados na coluna ID_PESSOA:")
    print(duplicatas_ID_PESSOA)
else:
    print("Não há IDs PESSOA duplicados.")


Registros duplicados na coluna ID_PESSOA:
       NU_NOTIFIC                       ID_PESSOA  \
25          32925  290320-290320-2006-09-04-F-4.0   
84          14736  292870-292870-1999-11-27-M-9.0   
93          14128  293135-293135-1982-08-18-F-4.0   
115           220  292740-292740-1983-06-14-M-9.0   
148          8846  293135-293135-1970-03-13-F-4.0   
...           ...                             ...   
38520       20950  291080-291080-2012-01-24-F-9.0   
38535       25098  292740-292740-1988-01-26-F-9.0   
38548       20178  291080-291080-1979-06-03-F-9.0   
38549       11171  291080-291080-1979-06-03-F-9.0   
38558       35083  291480-291480-1963-10-22-F-9.0   

                                          NOME  COMUNINF  ID_MN_RESI  \
25                          IRACI ABREU AGUIAR       NaN      290320   
84                   SERGIO MARTINS LIMA RAMOS  292870.0      292870   
93      MARIANA FERREIRA CARVALHO CAMPOS ALVES       NaN      293135   
115           RONALDO OLIVEIRA SO

In [60]:
# Lista das colunas a serem verificadas
colunas_verificar = ['ALRM_HIPOT', 'ALRM_PLAQ', 'ALRM_VOM', 'ALRM_SANG', 'ALRM_HEMAT', 'ALRM_ABDOM', 'ALRM_LETAR',
                     'ALRM_HEPAT', 'ALRM_LIQ', 'DT_ALRM', 'GRAV_PULSO', 'GRAV_CONV', 'GRAV_ENCH', 'GRAV_INSUF',
                     'GRAV_TAQUI', 'GRAV_EXTRE', 'GRAV_HIPOT', 'GRAV_HEMAT', 'GRAV_MELEN', 'GRAV_METRO', 'GRAV_SANG',
                     'GRAV_AST', 'GRAV_MIOC', 'GRAV_CONSC', 'GRAV_ORGAO', 'DT_GRAV', 'MANI_HEMOR', 'EPISTAXE',
                     'GENGIVO', 'METRO', 'PETEQUIAS', 'HEMATURA', 'SANGRAM', 'LACO_N', 'PLASMATICO', 'EVIDENCIA',
                     'PLAQ_MENOR', 'CON_FHD', 'COMPLICA', 'TP_SISTEMA', 'NDUPLIC_N', 'CS_FLXRET', 'FLXRECEBI']

# Criar um dicionário para armazenar os valores únicos de cada coluna
valores_unicos_por_coluna = {}

# Iterar sobre as colunas e obter os valores únicos
for coluna in colunas_verificar:
    valores_unicos_por_coluna[coluna] = df[coluna].unique()

# Exibir os valores únicos de cada coluna
for coluna, valores_unicos in valores_unicos_por_coluna.items():
    print(f"Valores únicos da coluna '{coluna}':")
    print(valores_unicos)


Valores únicos da coluna 'ALRM_HIPOT':
[nan  2.  1.]
Valores únicos da coluna 'ALRM_PLAQ':
[nan  1.  2.]
Valores únicos da coluna 'ALRM_VOM':
[nan  2.  1.]
Valores únicos da coluna 'ALRM_SANG':
[nan  2.  1.]
Valores únicos da coluna 'ALRM_HEMAT':
[nan  2.  1.]
Valores únicos da coluna 'ALRM_ABDOM':
[nan  2.  1.]
Valores únicos da coluna 'ALRM_LETAR':
[nan  1.  2.]
Valores únicos da coluna 'ALRM_HEPAT':
[nan  2.  1.]
Valores únicos da coluna 'ALRM_LIQ':
[nan  2.  1.]
Valores únicos da coluna 'DT_ALRM':
[nan '2015-06-10' '2015-07-30' '2016-08-05' '2015-11-16' '2016-02-19'
 '2017-01-29' '2017-01-27' '2017-01-31' '2017-02-02' '2017-02-03'
 '2017-10-24' '2017-10-27' '2018-04-01' '2018-05-02' '2018-08-12'
 '2018-10-04' '2018-12-16' '2019-01-08' '2019-01-16' '2019-01-21'
 '2019-01-18' '2019-01-29' '2019-04-09' '2019-01-31' '2019-01-23'
 '2019-02-04' '2019-01-28' '2019-02-08' '2019-02-19' '2019-02-11'
 '2019-02-05' '2019-02-15' '2019-02-13' '2019-02-21' '2019-02-17'
 '2019-02-23' '2019-02-28' 

In [57]:
# Exibir as primeiras linhas da coluna 'NU_ANO'
print(df['NU_ANO'].head())


0    2012
1    2013
2    2013
3    2013
4    2013
Name: NU_ANO, dtype: int64


In [58]:
# Excluir os valores NaN na coluna 'NU_ANO'
df_sem_nan = df.dropna(subset=['NU_ANO'])

# Verificar se há valores diferentes de 'YYYY' na coluna 'NU_ANO'
valores_diferentes = df_sem_nan['NU_ANO'].unique()
for valor in valores_diferentes:
    if valor != 'YYYY':
        print("Há valores diferentes de 'YYYY' na coluna 'NU_ANO'.")
        print("Valores diferentes encontrados:", valores_diferentes)
        break
else:
    print("Não há valores diferentes de 'YYYY' na coluna 'NU_ANO'.")


Há valores diferentes de 'YYYY' na coluna 'NU_ANO'.
Valores diferentes encontrados: [2012 2013 2014 2015 2016 2017 2018 2019]


In [56]:
# Verificar se há números na coluna 'NOME'
for nome in df['NOME']:
    if any(caracter.isdigit() for caracter in nome):
        print("Existem números na coluna 'NOME'.")
        break
else:
    print("Não existem números na coluna 'NOME'.")


Não existem números na coluna 'NOME'.


In [55]:
# Encontrar os valores únicos na coluna 'CS_SEXO'
valores_unicos = df['CS_SEXO'].unique()

# Exibir os valores únicos
print("Valores únicos na coluna 'CS_SEXO':")
print(valores_unicos)


Valores únicos na coluna 'CS_SEXO':
['M' 'F']


In [49]:
# Lista das colunas desejadas
colunas_desejadas = ['GRAV_PULSO', 'GRAV_CONV', 'GRAV_ENCH', 'GRAV_INSUF', 'GRAV_TAQUI', 'GRAV_EXTRE', 'GRAV_HIPOT',
                     'GRAV_HEMAT', 'GRAV_MELEN', 'GRAV_METRO', 'GRAV_SANG', 'GRAV_AST', 'GRAV_MIOC', 'GRAV_CONSC', 'GRAV_ORGAO']

# Iteração sobre as colunas desejadas
for coluna in colunas_desejadas:
    # Exibição dos valores únicos na coluna
    print(f"Valores únicos na coluna {coluna}:")
    print(df[coluna].unique())
    print()


Valores únicos na coluna GRAV_PULSO:
[nan  2.]

Valores únicos na coluna GRAV_CONV:
[nan  2.  1.]

Valores únicos na coluna GRAV_ENCH:
[nan  2.  1.]

Valores únicos na coluna GRAV_INSUF:
[nan  2.  1.]

Valores únicos na coluna GRAV_TAQUI:
[nan  2.  1.]

Valores únicos na coluna GRAV_EXTRE:
[nan  2.  1.]

Valores únicos na coluna GRAV_HIPOT:
[nan  2.  1.]

Valores únicos na coluna GRAV_HEMAT:
[nan  2.  1.]

Valores únicos na coluna GRAV_MELEN:
[nan  1.  2.]

Valores únicos na coluna GRAV_METRO:
[nan  2.  1.]

Valores únicos na coluna GRAV_SANG:
[nan  2.]

Valores únicos na coluna GRAV_AST:
[nan  2.]

Valores únicos na coluna GRAV_MIOC:
[nan  2.]

Valores únicos na coluna GRAV_CONSC:
[nan  2.]

Valores únicos na coluna GRAV_ORGAO:
[nan  2.  1.]



In [51]:
# Lista das colunas de população estimada
colunas_populacao_estimada = ['POPULAÇÃO ESTIMADA 2020', 'POPULAÇÃO ESTIMADA 2019', 'POPULAÇÃO ESTIMADA 2018',
                              'POPULAÇÃO ESTIMADA 2017', 'POPULAÇÃO ESTIMADA 2016', 'POPULAÇÃO ESTIMADA 2015',
                              'POPULAÇÃO ESTIMADA 2014', 'POPULAÇÃO ESTIMADA 2013', 'POPULAÇÃO ESTIMADA 2012',
                              'POPULAÇÃO ESTIMADA 2011']

# Variável para acompanhar se todos os valores são numéricos e positivos
todos_positivos = True

# Iteração sobre as colunas de população estimada
for coluna in colunas_populacao_estimada:
    # Excluir valores NaN e converter para string
    valores_validos = df[coluna].dropna().astype(str)
    # Verificar se todos os valores na coluna são numéricos e positivos
    if not valores_validos.str.isnumeric().all():
        todos_positivos = False
        print(f"Coluna {coluna}: Nem todos os valores são numéricos.")
    else:
        # Verificar se há algum valor negativo
        valores_negativos = valores_validos[valores_validos.astype(int) < 0]
        if not valores_negativos.empty:
            todos_positivos = False
            print(f"Coluna {coluna}: Há valores negativos.")
        # Verificar se há algum valor que não seja um número
        elif not valores_validos.str.match(r'^\d+$').all():
            todos_positivos = False
            print(f"Coluna {coluna}: Há valores não numéricos.")

# Se todos os valores forem positivos e numéricos, exibir uma mensagem
if todos_positivos:
    print("Todos os valores nas colunas de população estimada são numéricos e positivos.")


Coluna POPULAÇÃO ESTIMADA 2012: Nem todos os valores são numéricos.


In [53]:
# Encontrar os valores não numéricos na coluna 'POPULAÇÃO ESTIMADA 2012'
valores_nao_numericos = df.loc[~df['POPULAÇÃO ESTIMADA 2012'].astype(str).str.isnumeric(), 'POPULAÇÃO ESTIMADA 2012']

# Exibir os valores não numéricos, se houver
if not valores_nao_numericos.empty:
    print("Valores não numéricos na coluna 'POPULAÇÃO ESTIMADA 2012':")
    print(valores_nao_numericos)
else:
    print("Não há valores não numéricos na coluna 'POPULAÇÃO ESTIMADA 2012'.")


Valores não numéricos na coluna 'POPULAÇÃO ESTIMADA 2012':
0        2317-03-06
1        2317-03-06
2        1910-05-09
3        1944-09-08
4        1944-09-08
            ...    
38564    3455-05-26
38565    9322-05-17
38566    9322-05-17
38567    9322-05-17
38568    9322-05-17
Name: POPULAÇÃO ESTIMADA 2012, Length: 38569, dtype: object


In [46]:
# Encontrar os valores únicos na coluna ID_AGRAVO
valores_unicos_ID_AGRAVO = df['ID_AGRAVO'].unique()

# Exibir os valores únicos
print("Valores únicos na coluna ID_AGRAVO:")
print(valores_unicos_ID_AGRAVO)


Valores únicos na coluna ID_AGRAVO:
['A90']


In [45]:
# Verificar se há valores na coluna UF_RESI acima de 27
if (df['UF_RESI'] > 53).any():
    print("Há valores na coluna UF_RESI que estão acima de 53.")
else:
    print("Não há valores na coluna UF_RESI que estejam acima de 53.")


Não há valores na coluna UF_RESI que estejam acima de 53.


In [40]:
# Verificar se há valores negativos na coluna de idade
if (df['IDADE'] < 0).any():
    print("Há valores negativos na coluna de idade.")
else:
    print("Não há valores negativos na coluna de idade.")


Não há valores negativos na coluna de idade.


In [39]:
# Verificar se há NaN nas colunas específicas
nan_cols = ['NU_NOTIFIC', 'ID_PESSOA', 'NOME']
nan_values = df[nan_cols].isna().any()

# Exibir as colunas com valores NaN, se houver
for col, has_nan in nan_values.items():
    if has_nan:
        print(f"Há valores NaN na coluna {col}.")
    else:
        print(f"Não há valores NaN na coluna {col}.")


Não há valores NaN na coluna NU_NOTIFIC.
Não há valores NaN na coluna ID_PESSOA.
Não há valores NaN na coluna NOME.


In [36]:
import pandas as pd

# Suponha que df seja o seu DataFrame

# Converter todas as colunas para numérico, ignorando erros
df_numeric = df.apply(pd.to_numeric, errors='coerce')

# Verificar se há valores negativos em todo o DataFrame
if (df_numeric < 0).any().any():
    print("Há valores negativos no DataFrame.")
else:
    print("Não há valores negativos no DataFrame.")


Não há valores negativos no DataFrame.


In [6]:
# Etapa 7: Calcular o percentual de NaN em todo o banco de dados
percent_nan_total = df.isna().mean().mean() * 100
print(f"Percentual de NaN no banco de dados: {percent_nan_total:.2f}%")


Percentual de NaN no banco de dados: 57.31%


In [7]:
# Etapa 8: Retornar todas as colunas que possuem NaN
columns_with_nan = df.columns[df.isna().any()].tolist()
print("Colunas que possuem NaN:")
print(columns_with_nan)


Colunas que possuem NaN:
['COMUNINF', 'MUNICIPIO', 'ID_REGIONA', 'ID_UNIDADE', 'CS_GESTANT', 'CS_ESCOL_N', 'DT_INVEST', 'ID_OCUPA_N', 'FEBRE', 'MIALGIA', 'CEFALEIA', 'EXANTEMA', 'VOMITO', 'NAUSEA', 'DOR_COSTAS', 'CONJUNTVIT', 'ARTRITE', 'ARTRALGIA', 'PETEQUIA_N', 'LEUCOPENIA', 'LACO', 'DOR_RETRO', 'DIABETES', 'HEMATOLOG', 'HEPATOPAT', 'RENAL', 'HIPERTENSA', 'ACIDO_PEPT', 'AUTO_IMUNE', 'DT_CHIK_S1', 'DT_CHIK_S2', 'DT_PRNT', 'RES_CHIKS1', 'RES_CHIKS2', 'RESUL_PRNT', 'DT_SORO', 'RESUL_SORO', 'DT_NS1', 'RESUL_NS1', 'DT_VIRAL', 'RESUL_VI_N', 'DT_PCR', 'RESUL_PCR_', 'SOROTIPO', 'HISTOPA_N', 'IMUNOH_N', 'HOSPITALIZ', 'DT_INTERNA', 'UF', 'TPAUTOCTO', 'COUFINF', 'COPAISINF', 'CLASSI_FIN', 'CRITERIO', 'DOENCA_TRA', 'CLINC_CHIK', 'EVOLUCAO', 'DT_OBITO', 'DT_ENCERRA', 'ALRM_HIPOT', 'ALRM_PLAQ', 'ALRM_VOM', 'ALRM_SANG', 'ALRM_HEMAT', 'ALRM_ABDOM', 'ALRM_LETAR', 'ALRM_HEPAT', 'ALRM_LIQ', 'DT_ALRM', 'GRAV_PULSO', 'GRAV_CONV', 'GRAV_ENCH', 'GRAV_INSUF', 'GRAV_TAQUI', 'GRAV_EXTRE', 'GRAV_HIPOT', 'GRAV_

In [10]:
# Calcular o percentual de NaN para cada coluna que possui NaN
percent_nan_by_column = (df[columns_with_nan].isna().mean() * 100).round(2)

# Exibir o percentual de NaN para cada coluna na tela
for column, percent_nan in zip(columns_with_nan, percent_nan_by_column):
    print(f"Percentual de NaN na coluna '{column}': {percent_nan}%")


Percentual de NaN na coluna 'COMUNINF': 72.14%
Percentual de NaN na coluna 'MUNICIPIO': 96.77%
Percentual de NaN na coluna 'ID_REGIONA': 0.04%
Percentual de NaN na coluna 'ID_UNIDADE': 0.12%
Percentual de NaN na coluna 'CS_GESTANT': 0.01%
Percentual de NaN na coluna 'CS_ESCOL_N': 21.71%
Percentual de NaN na coluna 'DT_INVEST': 15.92%
Percentual de NaN na coluna 'ID_OCUPA_N': 83.88%
Percentual de NaN na coluna 'FEBRE': 58.3%
Percentual de NaN na coluna 'MIALGIA': 58.3%
Percentual de NaN na coluna 'CEFALEIA': 58.3%
Percentual de NaN na coluna 'EXANTEMA': 58.3%
Percentual de NaN na coluna 'VOMITO': 58.3%
Percentual de NaN na coluna 'NAUSEA': 58.3%
Percentual de NaN na coluna 'DOR_COSTAS': 58.3%
Percentual de NaN na coluna 'CONJUNTVIT': 58.3%
Percentual de NaN na coluna 'ARTRITE': 58.3%
Percentual de NaN na coluna 'ARTRALGIA': 58.3%
Percentual de NaN na coluna 'PETEQUIA_N': 58.3%
Percentual de NaN na coluna 'LEUCOPENIA': 58.3%
Percentual de NaN na coluna 'LACO': 58.3%
Percentual de NaN na 

In [13]:
# Selecionar todas as colunas de data no documento
date_columns = df.select_dtypes(include=['datetime64']).columns.tolist()

# Exibir as colunas de data
print("Colunas de data do documento:")
print(date_columns)


Colunas de data do documento:
[]


In [14]:
# Identificar todas as colunas que contêm 'DT' no nome
dt_columns = [col for col in df.columns if 'DT' in col]

# Exibir as colunas que contêm 'DT'
print("Colunas que possuem 'DT' no nome:")
print(dt_columns)


Colunas que possuem 'DT' no nome:
['DT_NOTIFIC', 'DT_SIN_PRI', 'DT_NASC', 'DT_INVEST', 'DT_CHIK_S1', 'DT_CHIK_S2', 'DT_PRNT', 'DT_SORO', 'DT_NS1', 'DT_VIRAL', 'DT_PCR', 'DT_INTERNA', 'DT_OBITO', 'DT_ENCERRA', 'DT_ALRM', 'DT_GRAV']


In [4]:
## Renomear as colunas no DataFrame original
df.rename(columns={'DT_NOTIFIC': 'Data_Notificação',
                   'DT_SIN_PRI': 'Data_Início_Sintomas_Principais',
                   'DT_NASC': 'Data_Nascimento',
                   'DT_INVEST': 'Data_Investigação',
                   'DT_CHIK_S1': 'Data_Chikungunya_Estágio_1',
                   'DT_CHIK_S2': 'Data_Chikungunya_Estágio_2',
                   'DT_PRNT': 'Data_Impressão',
                   'DT_SORO': 'Data_Teste_Sorologia',
                   'DT_NS1': 'Data_Teste_NS1',
                   'DT_VIRAL': 'Data_Teste_Viral',
                   'DT_PCR': 'Data_Teste_PCR',
                   'DT_INTERNA': 'Data_Internação',
                   'DT_OBITO': 'Data_Óbito',
                   'DT_ENCERRA': 'Data_Encerramento',
                   'DT_ALRM': 'Data_Alarme',
                   'DT_GRAV': 'Data_Gravidade'}, inplace=True)

# Selecionar apenas as colunas renomeadas
colunas_selecionadas = ['Data_Notificação', 'Data_Início_Sintomas_Principais', 'Data_Nascimento',
                        'Data_Investigação', 'Data_Chikungunya_Estágio_1', 'Data_Chikungunya_Estágio_2',
                        'Data_Impressão', 'Data_Teste_Sorologia', 'Data_Teste_NS1', 'Data_Teste_Viral',
                        'Data_Teste_PCR', 'Data_Internação', 'Data_Óbito', 'Data_Encerramento',
                        'Data_Alarme', 'Data_Gravidade']
df = df[colunas_selecionadas]

# Exibir o DataFrame com as colunas renomeadas
print("DataFrame com as colunas renomeadas:")
print(df)



DataFrame com as colunas renomeadas:
     Data_Notificação Data_Início_Sintomas_Principais Data_Nascimento  \
0          2012-12-31                      2012-12-30      1982-06-23   
1          2013-01-01                      2012-12-30      1984-07-26   
2          2013-01-01                      2012-12-31      1988-06-22   
3          2013-01-01                      2012-12-31      2004-12-29   
4          2013-01-01                      2012-12-31      1961-01-25   
...               ...                             ...             ...   
2217       2013-03-04                      2013-03-01      1981-02-19   
2218       2013-03-04                      2013-03-01      1996-09-02   
2219       2013-03-04                      2013-03-03      1993-11-12   
2220       2013-03-04                      2013-03-01      1956-01-28   
2221              NaN                             NaN             NaN   

     Data_Investigação  Data_Chikungunya_Estágio_1  \
0           2012-12-31          

In [56]:
# Verificar se a data de nascimento é anterior à data de óbito
validacao_nascimento_obito = (df['Data_Nascimento'] < df['Data_Óbito']).all()

# Verificar se a data de notificação é anterior à data de internação
validacao_notificacao_internacao = (df['Data_Notificação'] < df['Data_Internação']).all()

# Verificar se a data de notificação é anterior à data de encerramento
validacao_notificacao_encerramento = (df['Data_Notificação'] < df['Data_Encerramento']).all()

# Exibir os resultados das validações
print("Validação - Data de nascimento é anterior à data de óbito:", validacao_nascimento_obito)
print("Validação - Data de notificação é anterior à data de internação:", validacao_notificacao_internacao)
print("Validação - Data de notificação é anterior à data de encerramento:", validacao_notificacao_encerramento)


Validação - Data de nascimento é anterior à data de óbito: False
Validação - Data de notificação é anterior à data de internação: False
Validação - Data de notificação é anterior à data de encerramento: False


In [59]:
# Filtrar o DataFrame onde a Data de Nascimento é posterior à Data de Óbito
linha_nascimento_apos_obito = df[df['Data_Nascimento'] > df['Data_Óbito']]

# Exibir a linha onde ocorre o erro, se houver
if not linha_nascimento_apos_obito.empty:
    print("Linha onde Data de Nascimento é posterior à Data de Óbito:")
    print(linha_nascimento_apos_obito)
else:
    print("Não há nenhuma linha onde Data de Nascimento é posterior à Data de Óbito.")


Não há nenhuma linha onde Data de Nascimento é posterior à Data de Óbito.


In [61]:
# Filtrar o DataFrame onde a Data de Internação é posterior à Data de Óbito
linha_internacao_apos_obito = df[df['Data_Internação'] > df['Data_Óbito']]

# Se houver linhas onde a Data de Internação é posterior à Data de Óbito, exibir apenas as variáveis "Internação" e "Óbito" dessas linhas
if not linha_internacao_apos_obito.empty:
    print("Variáveis 'Internação' e 'Óbito' para as linhas onde Data de Internação é posterior à Data de Óbito:")
    print(linha_internacao_apos_obito[['Data_Internação', 'Data_Óbito']])
else:
    print("Não há nenhuma linha onde Data de Internação é posterior à Data de Óbito.")


Variáveis 'Internação' e 'Óbito' para as linhas onde Data de Internação é posterior à Data de Óbito:
     Data_Internação  Data_Óbito
6845      2013-05-25  2013-05-24


In [22]:
# Verificar se há alguma linha onde a Data de Nascimento é posterior a outra data
datas_nascimento_posterior = df['Data_Nascimento'] > df[['Data_Notificação', 'Data_Início_Sintomas_Principais', 'Data_Investigação',
                                                         'Data_Chikungunya_Estágio_1', 'Data_Chikungunya_Estágio_2',
                                                         'Data_Impressão', 'Data_Teste_Sorologia', 'Data_Teste_NS1',
                                                         'Data_Teste_Viral', 'Data_Teste_PCR', 'Data_Internação',
                                                         'Data_Óbito', 'Data_Encerramento', 'Data_Alarme', 'Data_Gravidade']].max(axis=1)

# Exibir a linha onde ocorre a inconsistência, se houver
if datas_nascimento_posterior.any():
    print("Há pelo menos uma linha onde a Data de Nascimento é posterior a outra data:")
    print(df[datas_nascimento_posterior])
else:
    print("Não há nenhuma linha onde a Data de Nascimento é posterior a outra data.")




Não há nenhuma linha onde a Data de Nascimento é posterior a outra data.


In [25]:
# Lista de colunas de datas a serem verificadas
datas_a_verificar = ['Data_Início_Sintomas_Principais', 'Data_Investigação',
                     'Data_Chikungunya_Estágio_1', 'Data_Chikungunya_Estágio_2',
                     'Data_Impressão', 'Data_Teste_Sorologia', 'Data_Teste_NS1',
                     'Data_Teste_Viral', 'Data_Teste_PCR', 'Data_Internação',
                     'Data_Alarme', 'Data_Gravidade']

# Verificar se há datas posteriores a 'Data_Óbito' e 'Data_Encerramento' em cada linha
for coluna in datas_a_verificar:
    datas_posterior_obito = df[coluna] > df['Data_Óbito']
    datas_posterior_encerramento = df[coluna] > df['Data_Encerramento']

    # Exibir as linhas onde ocorrem as inconsistências, se houver
    if datas_posterior_obito.any():
        print(f"Para a coluna '{coluna}', há pelo menos uma linha onde há datas posteriores à Data de Óbito:")
        print(df[datas_posterior_obito])

    if datas_posterior_encerramento.any():
        print(f"Para a coluna '{coluna}', há pelo menos uma linha onde há datas posteriores à Data de Encerramento:")
        print(df[datas_posterior_encerramento])



Para a coluna 'Data_Investigação', há pelo menos uma linha onde há datas posteriores à Data de Encerramento:
    Data_Notificação Data_Início_Sintomas_Principais Data_Nascimento  \
822       2013-02-06                      2013-02-05      1988-09-17   

    Data_Investigação Data_Chikungunya_Estágio_1 Data_Chikungunya_Estágio_2  \
822        2014-02-17                        NaT                        NaT   

    Data_Impressão Data_Teste_Sorologia Data_Teste_NS1 Data_Teste_Viral  \
822            NaT           2013-02-10            NaT              NaT   

    Data_Teste_PCR Data_Internação Data_Óbito Data_Encerramento Data_Alarme  \
822            NaT      2014-02-05        NaT        2013-04-08         NaT   

    Data_Gravidade  
822            NaT  
Para a coluna 'Data_Teste_Sorologia', há pelo menos uma linha onde há datas posteriores à Data de Encerramento:
     Data_Notificação Data_Início_Sintomas_Principais Data_Nascimento  \
26         2013-01-04                      2012-12

In [26]:
# Acessar a data de internação das linhas especificadas
datas_internacao = df.loc[[26, 1120, 1673, 1831], 'Data_Internação']

# Exibir as datas de internação das linhas especificadas
print(datas_internacao)


26            NaT
1120   2013-02-08
1673          NaT
1831          NaT
Name: Data_Internação, dtype: datetime64[ns]


Não há registro de internação das linhas 26, 1120, 1673 e 1831 para saber se há inconsistência entre datas de internação, óbito e ou demais.

Não há valores iguais a '-' em nenhuma posição.
DataFrame após a exclusão de NaN:
Empty DataFrame
Columns: [Data_Notificação, Data_Início_Sintomas_Principais, Data_Nascimento, Data_Investigação, Data_Chikungunya_Estágio_1, Data_Chikungunya_Estágio_2, Data_Impressão, Data_Teste_Sorologia, Data_Teste_NS1, Data_Teste_Viral, Data_Teste_PCR, Data_Internação, Data_Óbito, Data_Encerramento, Data_Alarme, Data_Gravidade]
Index: []
